spring:
  profiles:
    active: active
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_null
jwt:
  secret: your-256-bit-secret-key-must-be-long-enough-for-hs256
  expiration: 86400000
